# -*- coding: utf-8 -*-

PANEL_ID = "1c253d20-7da2-4ab0-b991-696df704f713"
PANEL_TITLE = "BB Issue Tracker"

COMMAND_APPDOMAIN_KEY = "BB_ISSUE_TRACKER_PENDING_COMMAND_V1"

COMMAND_REFRESH = "REFRESH"
COMMAND_NEW_ISSUE = "NEW_ISSUE"
COMMAND_MY_ISSUES = "MY_ISSUES"

REQUEST_GET_CONTEXT = "GET_CONTEXT"
REQUEST_PICK_LOCATION = "PICK_LOCATION"
REQUEST_CAPTURE_SNAPSHOT = "CAPTURE_SNAPSHOT"
REQUEST_NAVIGATE_LOCATION = "NAVIGATE_LOCATION"
REQUEST_NAVIGATE_VIEW = "NAVIGATE_VIEW"
REQUEST_SYNC_MARKERS = "SYNC_MARKERS"
REQUEST_CLEAR_MARKERS = "CLEAR_MARKERS"

SCHEMA_VERSION = "1.0"
